// Code generated by hertz generator.

package student

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stuaddinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stuqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}
