// Code generated by hertz generator.

package student

import (
	"context"
	"sync"

	student "example.com/m/biz/model/student"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var students sync.Map

// Get .
// @router /query [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.QueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if st,ok:=students.Load(req.ID);ok{
		resp := st.(*student.Student)
		c.JSON(consts.StatusOK, resp)
		return
	}	
	c.JSON(consts.StatusNotFound, nil)
}

// Add .
// @router /addinfo [POST]
func Add(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.Student
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	hlog.Tracef("add student info:%v",req)
	students.Store(req.ID,&req)
	resp := new(student.Student)

	c.JSON(consts.StatusOK, resp)
}
