// Code generated by hertz generator.

package example

import (
	"context"

	example "example.com/m/biz/model/hello/example"
	"github.com/cloudwego/hertz/pkg/app"
)

// handler path: biz/handler/hello/example/hello_service.go
// 其中 "hello/example" 是 thrift idl 的 namespace
// "hello_service.go" 是 thrift idl 中 service 的名字，所有 service 定义的方法都会生成在这个文件中

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
			c.String(400, err.Error())
			return
	}

	resp := new(example.HelloResp)

	// 你可以修改整个函数的逻辑，而不仅仅局限于当前模板
	resp.RespBody = "hello," + req.Name // 添加的逻辑

	c.JSON(200, resp)
}
