// Code generated by hertz generator.

package student

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"sync"

	student "example.com/m/biz/model/hertz/student"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var students sync.Map

// StuAddInfo .
// @router /add-student-info [POST]
func StuAddInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.Student
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	hlog.Tracef("add student info:%v", req)
	//Go的sync.Mapm没有返回错误的机制
	students.Store(req.Id, &req)
	c.String(consts.StatusOK, "添加成功\n")
}

// StuQuery .
// @router /query [GET]
func StuQuery(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.QueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if st, ok := students.Load(req.Id); ok {
		resp := st.(*student.Student)
		c.JSON(consts.StatusOK, resp)
		return
	}
	c.String(consts.StatusNotFound, "查询失败\n")
}
