// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	student "example.com/m/biz/router/student"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	student.Register(r)
}
