// Code generated by hertz generator.

package hello

import (
	"context"
	"sync"

	hello "example.com/m/biz/model/hertz/hello"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// 存储学生信息
var students sync.Map

// StuAddInfo .
// @router /add-student-info [POST]
func StuAddInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello.Student
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello.Student)

	c.JSON(consts.StatusOK, resp)
}

// StuQuery .
// @router /query [POST]
func StuQuery(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello.QueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello.Student)

	c.JSON(consts.StatusOK, resp)
}
