// Code generated by hertz generator.

package demo

import (
	"context"
	"example.com/m/biz/model/demo"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"sync"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var students sync.Map

// Register .
// @router /add-student-info [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo.Student
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	hlog.Tracef("add student info:%v", req)
	//Go的sync.Mapm没有返回错误的机制
	students.Store(req, &req)
	c.String(consts.StatusOK, "添加成功\n")
}

// Query .
// @router /query [GET]
func Query(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo.QueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(demo.Student)

	c.JSON(consts.StatusOK, resp)
}
