// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	demo "example.com/m/biz/router/demo"
	hello_example "example.com/m/biz/router/hello/example"
	student "example.com/m/biz/router/student"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	demo.Register(r)

	student.Register(r)

	hello_example.Register(r)
}
